apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment-blue
  labels:
    app: webapp
    environment: prod
    version: blue
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
        environment: prod
        version: blue

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment-green
  labels:
    app: webapp
    environment: prod
    version: green
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
        environment: prod
        version: green