apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml  

commonLabels:
  app: webapp

configMapGenerator:
- name: webapp-config-blue
  files:
    - .env.blue
- name: webapp-config-green
  files:
    - .env.green