# base/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: webapp-image:stable
        ports:
        - name: webapp
          containerPort: 3000
        envFrom:
        - configMapRef:
            name: webapp-config
        livenessProbe:
          httpGet:
            path: /health
            port: 3000