apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - hpa.yaml

commonLabels:
  app: webapp

configMapGenerator:
- name: webapp-config
  namespace: webapp
  files:
    - .env
generatorOptions:
  disableNameSuffixHash: true