apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  labels:
    app: webapp
  namespace: webapp
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: webapp